require("core.plugins_config.gruvbox")
require("core.plugins_config.lualine")
require("core.plugins_config.nvim-tree")
require("core.plugins_config.treesitter")
require("core.plugins_config.telescope")